perfumes = [
    
 {"nombre": "Pure Romance","marca": "Victoria's Secret","familia": "Floral Dulce","notas_salida": ["frambuesa", "mandarina"],
        "notas_corazon": ["jazmín", "peonía"],
        "notas_fondo": ["vainilla", "musk"],
        "intensidad": "moderada",
        "duracion": 6,
        "clima": "todo el año",
        "ocasion": "cita",
        "genero": "femenino"
    },
    {
        "nombre": "Velvet Glow",
        "marca": "Victoria's Secret",
        "familia": "Oriental Dulce",
        "notas_salida": ["ciruela", "pomelo"],
        "notas_corazon": ["orquídea", "jazmín"],
        "notas_fondo": ["ámbar", "vainilla"],
        "intensidad": "fuerte",
        "duracion": 8,
        "clima": "frío",
        "ocasion": "noche",
        "genero": "femenino"
    },
    {
        "nombre": "Dream Petals",
        "marca": "Victoria's Secret",
        "familia": "Floral",
        "notas_salida": ["bergamota"],
        "notas_corazon": ["rosa", "lirio"],
        "notas_fondo": ["madera suave"],
        "intensidad": "suave",
        "duracion": 4,
        "clima": "primavera",
        "ocasion": "diario",
        "genero": "femenino"
    },
    {
        "nombre": "Berry Kiss",
        "marca": "Victoria's Secret",
        "familia": "Frutal Dulce",
        "notas_salida": ["fresa", "mora"],
        "notas_corazon": ["flor de cerezo"],
        "notas_fondo": ["azúcar", "almizcle"],
        "intensidad": "moderada",
        "duracion": 5,
        "clima": "calor",
        "ocasion": "casual",
        "genero": "femenino"
    },
    {
        "nombre": "Angel Touch",
        "marca": "Victoria's Secret",
        "familia": "Floral Fresco",
        "notas_salida": ["limón", "hojas verdes"],
        "notas_corazon": ["jazmín", "magnolia"],
        "notas_fondo": ["almizcle blanco"],
        "intensidad": "suave",
        "duracion": 4,
        "clima": "verano",
        "ocasion": "diario",
        "genero": "femenino"
    },
    {
        "nombre": "Candy Mist",
        "marca": "Victoria's Secret",
        "familia": "Dulce",
        "notas_salida": ["caramelo"],
        "notas_corazon": ["algodón de azúcar"],
        "notas_fondo": ["vainilla"],
        "intensidad": "moderada",
        "duracion": 5,
        "clima": "todo el año",
        "ocasion": "casual",
        "genero": "femenino"
    },
    {
        "nombre": "Midnight Blush",
        "marca": "Victoria's Secret",
        "familia": "Floral Oriental",
        "notas_salida": ["frambuesa"],
        "notas_corazon": ["rosas rojas", "jazmín"],
        "notas_fondo": ["ámbar oscuro"],
        "intensidad": "fuerte",
        "duracion": 7,
        "clima": "frío",
        "ocasion": "noche",
        "genero": "femenino"
    },
    {
        "nombre": "Aqua Shine",
        "marca": "Victoria's Secret",
        "familia": "Fresco Acuático",
        "notas_salida": ["pepino", "cítricos"],
        "notas_corazon": ["nenúfar"],
        "notas_fondo": ["musk acuático"],
        "intensidad": "suave",
        "duracion": 3,
        "clima": "verano",
        "ocasion": "diario",
        "genero": "femenino"
    },
    {
        "nombre": "Love Spell Bloom",
        "marca": "Victoria's Secret",
        "familia": "Frutal Floral",
        "notas_salida": ["durazno", "cereza"],
        "notas_corazon": ["flor blanca"],
        "notas_fondo": ["vainilla ligera"],
        "intensidad": "moderada",
        "duracion": 5,
        "clima": "calor",
        "ocasion": "casual",
        "genero": "femenino"
    },
    {
        "nombre": "Rose Seduction",
        "marca": "Victoria's Secret",
        "familia": "Floral",
        "notas_salida": ["rosa fresca"],
        "notas_corazon": ["peonía"],
        "notas_fondo": ["madera suave"],
        "intensidad": "moderada",
        "duracion": 6,
        "clima": "primavera",
        "ocasion": "romántica",
        "genero": "femenino"
    },
    {
        "nombre": "Black Opium",
        "marca": "Yves Saint Laurent",
        "familia": "Oriental Dulce",
        "notas_salida": ["pera", "pimienta rosa"],
        "notas_corazon": ["café", "jazmín"],
        "notas_fondo": ["vainilla", "cedro"],
        "intensidad": "fuerte",
        "duracion": 9,
        "clima": "frío",
        "ocasion": "noche",
        "genero": "femenino"
    },
    {
        "nombre": "Libre",
        "marca": "Yves Saint Laurent",
        "familia": "Floral Oriental",
        "notas_salida": ["lavanda", "mandarina"],
        "notas_corazon": ["jazmín", "azahar"],
        "notas_fondo": ["vainilla", "ámbar"],
        "intensidad": "moderada",
        "duracion": 7,
        "clima": "todo el año",
        "ocasion": "formal",
        "genero": "femenino"
    },
    {
        "nombre": "Mon Paris",
        "marca": "Yves Saint Laurent",
        "familia": "Frutal Floral",
        "notas_salida": ["fresa", "frambuesa"],
        "notas_corazon": ["peonía", "jazmín"],
        "notas_fondo": ["musk blanco", "ámbar ligero"],
        "intensidad": "moderada",
        "duracion": 6,
        "clima": "primavera",
        "ocasion": "romántica",
        "genero": "femenino"
    },
    {
        "nombre": "Y Eau de Parfum",
        "marca": "Yves Saint Laurent",
        "familia": "Aromático Amaderado",
        "notas_salida": ["manzana", "jengibre"],
        "notas_corazon": ["salvia", "geranio"],
        "notas_fondo": ["cedro", "fava tonka"],
        "intensidad": "fuerte",
        "duracion": 8,
        "clima": "todo el año",
        "ocasion": "casual",
        "genero": "masculino"
    },
    {
        "nombre": "La Nuit de L’Homme",
        "marca": "Yves Saint Laurent",
        "familia": "Oriental Especiado",
        "notas_salida": ["cardamomo"],
        "notas_corazon": ["lavanda", "cedro"],
        "notas_fondo": ["vetiver", "madera oscura"],
        "intensidad": "fuerte",
        "duracion": 7,
        "clima": "frío",
        "ocasion": "noche",
        "genero": "masculino"
    },
    {
        "nombre": "L’Homme",
        "marca": "Yves Saint Laurent",
        "familia": "Amaderado Fresco",
        "notas_salida": ["bergamota", "jengibre"],
        "notas_corazon": ["violeta", "pimienta"],
        "notas_fondo": ["vetiver", "cedro"],
        "intensidad": "moderada",
        "duracion": 6,
        "clima": "primavera",
        "ocasion": "diario",
        "genero": "masculino"
    },
    {
        "nombre": "Manifesto",
        "marca": "Yves Saint Laurent",
        "familia": "Oriental Vainilla",
        "notas_salida": ["grosella negra"],
        "notas_corazon": ["jazmín sambac"],
        "notas_fondo": ["madera de cachemira", "vainilla"],
        "intensidad": "moderada",
        "duracion": 7,
        "clima": "otoño",
        "ocasion": "formal",
        "genero": "femenino"
    },
    {
        "nombre": "Belle d’Opium",
        "marca": "Yves Saint Laurent",
        "familia": "Oriental Especiado",
        "notas_salida": ["pelargonio", "jazmín"],
        "notas_corazon": ["incienso", "melocotón"],
        "notas_fondo": ["sándalo", "musk"],
        "intensidad": "fuerte",
        "duracion": 8,
        "clima": "frío",
        "ocasion": "noche",
        "genero": "femenino"
    },
    {
        "nombre": "Saharienne",
        "marca": "Yves Saint Laurent",
        "familia": "Cítrico Fresco",
        "notas_salida": ["limón", "bergamota"],
        "notas_corazon": ["flor de azahar"],
        "notas_fondo": ["almizcle suave"],
        "intensidad": "suave",
        "duracion": 4,
        "clima": "verano",
        "ocasion": "diario",
        "genero": "femenino"
    },
    {
        "nombre": "Opium",
        "marca": "Yves Saint Laurent",
        "familia": "Oriental Clásico",
        "notas_salida": ["mandarina", "clavo"],
        "notas_corazon": ["jazmín", "mirra"],
        "notas_fondo": ["pachuli", "bálsamo"],
        "intensidad": "fuerte",
        "duracion": 10,
        "clima": "frío",
        "ocasion": "formal",
        "genero": "femenino"
    },
    
      {
        "nombre": "John Varvatos Classic",
        "marca": "John Varvatos",
        "familia": "Amaderado Oriental",
        "notas_salida": ["ciruela", "tamarindo"],
        "notas_corazon": ["canela", "pimienta"],
        "notas_fondo": ["sándalo", "cedro"],
        "intensidad": "moderada",
        "duracion": 6,
        "clima": "otoño",
        "ocasion": "formal",
        "genero": "masculino"
    },
    {
        "nombre": "John Varvatos Vintage",
        "marca": "John Varvatos",
        "familia": "Amaderado Chipre",
        "notas_salida": ["tabaco", "bayas de enebro"],
        "notas_corazon": ["lavanda", "jazmín"],
        "notas_fondo": ["haba tonka", "pachuli"],
        "intensidad": "fuerte",
        "duracion": 8,
        "clima": "frío",
        "ocasion": "noche",
        "genero": "masculino"
    },
    {
        "nombre": "John Varvatos Artisan",
        "marca": "John Varvatos",
        "familia": "Cítrico Aromático",
        "notas_salida": ["clementina", "tomillo"],
        "notas_corazon": ["jengibre", "flores blancas"],
        "notas_fondo": ["ámbar", "madera suave"],
        "intensidad": "moderada",
        "duracion": 5,
        "clima": "verano",
        "ocasion": "casual",
        "genero": "masculino"
    },
    {
        "nombre": "John Varvatos Artisan Blu",
        "marca": "John Varvatos",
        "familia": "Acuático Aromático",
        "notas_salida": ["bergamota", "albahaca"],
        "notas_corazon": ["salvia", "flor de azahar"],
        "notas_fondo": ["cedro", "pachuli"],
        "intensidad": "moderada",
        "duracion": 6,
        "clima": "verano",
        "ocasion": "diario",
        "genero": "masculino"
    },
    {
        "nombre": "John Varvatos Artisan Pure",
        "marca": "John Varvatos",
        "familia": "Cítrico Fresco",
        "notas_salida": ["mandarina", "bergamota"],
        "notas_corazon": ["jengibre", "tomillo"],
        "notas_fondo": ["almizcle", "madera suave"],
        "intensidad": "suave",
        "duracion": 4,
        "clima": "primavera",
        "ocasion": "diario",
        "genero": "masculino"
    },
    {
        "nombre": "John Varvatos Dark Rebel",
        "marca": "John Varvatos",
        "familia": "Amaderado Cuero",
        "notas_salida": ["ron", "tabaco"],
        "notas_corazon": ["cuero", "resinas"],
        "notas_fondo": ["incienso", "madera oscura"],
        "intensidad": "fuerte",
        "duracion": 9,
        "clima": "frío",
        "ocasion": "noche",
        "genero": "masculino"
    },
    {
        "nombre": "John Varvatos Dark Rebel Rider",
        "marca": "John Varvatos",
        "familia": "Cuero Oriental",
        "notas_salida": ["citrón", "pimienta"],
        "notas_corazon": ["cuero", "resinas balsámicas"],
        "notas_fondo": ["vainilla", "ámbar"],
        "intensidad": "fuerte",
        "duracion": 8,
        "clima": "otoño",
        "ocasion": "formal",
        "genero": "masculino"
    },
    {
        "nombre": "John Varvatos Oud",
        "marca": "John Varvatos",
        "familia": "Oriental Amaderado",
        "notas_salida": ["canela", "nuez moscada"],
        "notas_corazon": ["rosa", "jazmín"],
        "notas_fondo": ["oud", "incienso"],
        "intensidad": "muy fuerte",
        "duracion": 10,
        "clima": "invierno",
        "ocasion": "noche",
        "genero": "masculino"
    },
    {
        "nombre": "John Varvatos XX Artisan",
        "marca": "John Varvatos",
        "familia": "Aromático Fresco",
        "notas_salida": ["bergamota", "manzana"],
        "notas_corazon": ["salvia", "geranio"],
        "notas_fondo": ["madera ámbar", "almizcle"],
        "intensidad": "moderada",
        "duracion": 6,
        "clima": "primavera",
        "ocasion": "casual",
        "genero": "masculino"
    },
    {
        "nombre": "John Varvatos XX Indigo",
        "marca": "John Varvatos",
        "familia": "Aromático Especiado",
        "notas_salida": ["menta", "limón"],
        "notas_corazon": ["cardamomo", "romero"],
        "notas_fondo": ["sándalo", "almizcle"],
        "intensidad": "moderada",
        "duracion": 5,
        "clima": "verano",
        "ocasion": "diario",
        "genero": "masculino"
    }, 
    
     {
    "nombre": "Dior Sauvage",
    "marca": "Dior",
    "familia": "Aromática fougère",
    "notas_salida": ["bergamota", "pimienta"],
    "notas_corazon": ["lavanda", "pimienta rosa", "geranio"],
    "notas_fondo": ["ambroxan", "cedro", "labdanum"],
    "intensidad": "Fuerte",
    "duracion": 9,
    "clima": "Cálido / templado",
    "ocasion": "Casual, noche",
    "genero": "Masculino"
  },
  {
    "nombre": "Dior Homme Intense",
    "marca": "Dior",
    "familia": "Amaderada floral",
    "notas_salida": ["lavanda"],
    "notas_corazon": ["iris", "almizcle", "peral"],
    "notas_fondo": ["vetiver", "cedro"],
    "intensidad": "Fuerte",
    "duracion": 10,
    "clima": "Frío",
    "ocasion": "Formal, noche",
    "genero": "Masculino"
  },
  {
    "nombre": "Miss Dior",
    "marca": "Dior",
    "familia": "Chipre floral",
    "notas_salida": ["bergamota"],
    "notas_corazon": ["rosa", "peonía", "iris"],
    "notas_fondo": ["almizcle blanco", "vainilla", "haba tonka"],
    "intensidad": "Moderada",
    "duracion": 8,
    "clima": "Templado",
    "ocasion": "Día, romántica",
    "genero": "Femenino"
  },
  {
    "nombre": "J'adore",
    "marca": "Dior",
    "familia": "Floral",
    "notas_salida": ["ylang-ylang", "bergamota"],
    "notas_corazon": ["rosa damascena", "jazmín"],
    "notas_fondo": ["sándalo", "vainilla"],
    "intensidad": "Moderada",
    "duracion": 8,
    "clima": "Caluroso",
    "ocasion": "Día, formal",
    "genero": "Femenino"
  },
  {
    "nombre": "Fahrenheit",
    "marca": "Dior",
    "familia": "Aromática amaderada",
    "notas_salida": ["lavanda", "mandarina"],
    "notas_corazon": ["violeta", "nuez moscada"],
    "notas_fondo": ["cuero", "vetiver", "almizcle"],
    "intensidad": "Fuerte",
    "duracion": 10,
    "clima": "Frío",
    "ocasion": "Noche",
    "genero": "Masculino"
  },
  {
    "nombre": "Dior Addict",
    "marca": "Dior",
    "familia": "Oriental floral",
    "notas_salida": ["frescura verde"],
    "notas_corazon": ["jazmín", "rosa"],
    "notas_fondo": ["vainilla", "sándalo"],
    "intensidad": "Fuerte",
    "duracion": 9,
    "clima": "Frío",
    "ocasion": "Noche",
    "genero": "Femenino"
  },
  {
    "nombre": "Dior Homme",
    "marca": "Dior",
    "familia": "Amaderada floral",
    "notas_salida": ["lavanda", "bergamota"],
    "notas_corazon": ["iris", "cacao"],
    "notas_fondo": ["ámbar", "vetiver"],
    "intensidad": "Moderada",
    "duracion": 8,
    "clima": "Templado",
    "ocasion": "Oficina, formal",
    "genero": "Masculino"
  },
  {
    "nombre": "Poison Girl",
    "marca": "Dior",
    "familia": "Oriental vainilla",
    "notas_salida": ["naranja amarga"],
    "notas_corazon": ["rosa de Damasco", "neroli"],
    "notas_fondo": ["vainilla", "haba tonka", "almizcle"],
    "intensidad": "Fuerte",
    "duracion": 9,
    "clima": "Frío",
    "ocasion": "Noche, fiesta",
    "genero": "Femenino"
  },
  {
    "nombre": "Hypnotic Poison",
    "marca": "Dior",
    "familia": "Oriental vainilla",
    "notas_salida": ["coco", "ciruela"],
    "notas_corazon": ["jazmín", "tuberosa"],
    "notas_fondo": ["vainilla", "almendra", "sándalo"],
    "intensidad": "Muy fuerte",
    "duracion": 10,
    "clima": "Frío",
    "ocasion": "Noche",
    "genero": "Femenino"
  },
  {
    "nombre": "Dune",
    "marca": "Dior",
    "familia": "Oriental floral",
    "notas_salida": ["mandarina", "aldehídos"],
    "notas_corazon": ["rosa", "ylang-ylang"],
    "notas_fondo": ["ámbar", "sándalo", "vainilla"],
    "intensidad": "Moderada",
    "duracion": 7,
    "clima": "Templado",
    "ocasion": "Día",
    "genero": "Femenino"
  },
  {
    "nombre": "Chanel No. 5",
    "marca": "Chanel",
    "familia": "Floral Aldehídica",
    "notas_salida": ["aldehídos", "bergamota", "neroli"],
    "notas_corazon": ["jazmín", "rosa", "ylang-ylang"],
    "notas_fondo": ["sándalo", "vainilla", "vetiver"],
    "intensidad": "Fuerte",
    "duracion": 9,
    "clima": "Frío / templado",
    "ocasion": "Formal, noche",
    "genero": "Femenino"
  },
  {
    "nombre": "Coco Mademoiselle",
    "marca": "Chanel",
    "familia": "Oriental Fresco",
    "notas_salida": ["naranja", "bergamota"],
    "notas_corazon": ["rosa", "jazmín"],
    "notas_fondo": ["patchouli", "vainilla", "almizcle blanco"],
    "intensidad": "Moderada",
    "duracion": 9,
    "clima": "Todo el año",
    "ocasion": "Formal, romántica",
    "genero": "Femenino"
  },
  {
    "nombre": "Bleu de Chanel",
    "marca": "Chanel",
    "familia": "Amaderada Aromática",
    "notas_salida": ["limón", "toronja", "menta"],
    "notas_corazon": ["jengibre", "jazmín"],
    "notas_fondo": ["incienso", "cedro", "sándalo"],
    "intensidad": "Fuerte",
    "duracion": 9,
    "clima": "Templado",
    "ocasion": "Casual, noche",
    "genero": "Masculino"
  },
  {
    "nombre": "Chance Eau Tendre",
    "marca": "Chanel",
    "familia": "Frutal Floral",
    "notas_salida": ["toronja", "membrillo"],
    "notas_corazon": ["jazmín", "jacinto"],
    "notas_fondo": ["almizcle blanco", "ámbar"],
    "intensidad": "Suave",
    "duracion": 6,
    "clima": "Primavera / verano",
    "ocasion": "Diario",
    "genero": "Femenino"
  },
  {
    "nombre": "Allure Homme Sport",
    "marca": "Chanel",
    "familia": "Cítrico Amaderado",
    "notas_salida": ["mandarina", "naranja"],
    "notas_corazon": ["pimienta", "neroli"],
    "notas_fondo": ["vainilla", "almizcle", "ámbar"],
    "intensidad": "Moderada",
    "duracion": 8,
    "clima": "Verano",
    "ocasion": "Casual, deporte",
    "genero": "Masculino"
  },
  {
    "nombre": "Gabrielle",
    "marca": "Chanel",
    "familia": "Floral",
    "notas_salida": ["toronja", "mandarina"],
    "notas_corazon": ["ylang-ylang", "jazmín", "nardo"],
    "notas_fondo": ["sándalo", "almizcle"],
    "intensidad": "Moderada",
    "duracion": 7,
    "clima": "Primavera",
    "ocasion": "Diario / formal",
    "genero": "Femenino"
  },
  {
    "nombre": "Chance Eau Fraîche",
    "marca": "Chanel",
    "familia": "Cítrico Floral",
    "notas_salida": ["limón", "cedrón"],
    "notas_corazon": ["jazmín"],
    "notas_fondo": ["madera de teca", "almizcle"],
    "intensidad": "Suave",
    "duracion": 5,
    "clima": "Verano",
    "ocasion": "Diario",
    "genero": "Femenino"
  },
  {
    "nombre": "Egoiste Platinum",
    "marca": "Chanel",
    "familia": "Aromática",
    "notas_salida": ["lavanda", "romero"],
    "notas_corazon": ["geranio", "clavo"],
    "notas_fondo": ["ámbar", "cedro", "musgo"],
    "intensidad": "Fuerte",
    "duracion": 8,
    "clima": "Templado",
    "ocasion": "Formal",
    "genero": "Masculino"
  },
  {
    "nombre": "Coco Noir",
    "marca": "Chanel",
    "familia": "Oriental Amaderado",
    "notas_salida": ["toronja", "bergamota"],
    "notas_corazon": ["rosa", "narciso"],
    "notas_fondo": ["patchouli", "sándalo", "vainilla"],
    "intensidad": "Fuerte",
    "duracion": 9,
    "clima": "Frío",
    "ocasion": "Noche",
    "genero": "Femenino"
  },
  {
    "nombre": "Pour Monsieur",
    "marca": "Chanel",
    "familia": "Cítrico Aromático",
    "notas_salida": ["limón", "neroli"],
    "notas_corazon": ["cardamomo", "jengibre"],
    "notas_fondo": ["vetiver", "musgo"],
    "intensidad": "Moderada",
    "duracion": 7,
    "clima": "Primavera / verano",
    "ocasion": "Oficina / casual",
    "genero": "Masculino"
  },
  {
    "nombre": "Allure",
    "marca": "Chanel",
    "familia": "Oriental Floral",
    "notas_salida": ["limón", "melocotón"],
    "notas_corazon": ["jazmín", "rosa", "lirio"],
    "notas_fondo": ["vainilla", "sándalo"],
    "intensidad": "Moderada",
    "duracion": 8,
    "clima": "Templado",
    "ocasion": "Formal / romántica",
    "genero": "Femenino"
  },
  
  {
    "nombre": "Si",
    "marca": "Armani",
    "familia": "Chipre Frutal",
    "notas_salida": ["grosella negra"],
    "notas_corazon": ["rosa", "freesia"],
    "notas_fondo": ["vainilla", "patchouli", "madera"],
    "intensidad": "Moderada",
    "duracion": 8,
    "clima": "Otoño",
    "ocasion": "Formal / romántica",
    "genero": "Femenino"
  },
  {
    "nombre": "Si Passione",
    "marca": "Armani",
    "familia": "Floral Frutal",
    "notas_salida": ["pera", "grosella negra"],
    "notas_corazon": ["rosa", "jazmín"],
    "notas_fondo": ["vainilla", "cedro"],
    "intensidad": "Fuerte",
    "duracion": 8,
    "clima": "Primavera",
    "ocasion": "Noche / cita",
    "genero": "Femenino"
  },
  {
    "nombre": "Acqua di Gio",
    "marca": "Armani",
    "familia": "Acuático Cítrico",
    "notas_salida": ["bergamota", "limón"],
    "notas_corazon": ["jazmín", "violeta"],
    "notas_fondo": ["almizcle", "cedro"],
    "intensidad": "Suave",
    "duracion": 6,
    "clima": "Verano",
    "ocasion": "Diario",
    "genero": "Masculino"
  },
  {
    "nombre": "Acqua di Gio Profumo",
    "marca": "Armani",
    "familia": "Acuático Amaderado",
    "notas_salida": ["bergamota", "incienso"],
    "notas_corazon": ["salvia", "romero"],
    "notas_fondo": ["patchouli", "almizcle"],
    "intensidad": "Fuerte",
    "duracion": 9,
    "clima": "Templado / frío",
    "ocasion": "Formal / noche",
    "genero": "Masculino"
  },
  {
    "nombre": "Armani Code",
    "marca": "Armani",
    "familia": "Oriental Especiado",
    "notas_salida": ["limón", "bergamota"],
    "notas_corazon": ["anís estrellado", "olivo"],
    "notas_fondo": ["haba tonka", "madera"],
    "intensidad": "Moderada",
    "duracion": 8,
    "clima": "Frío",
    "ocasion": "Noche",
    "genero": "Masculino"
  },
  {
    "nombre": "Armani Code Profumo",
    "marca": "Armani",
    "familia": "Oriental Ambarado",
    "notas_salida": ["cardamomo", "mandarina verde"],
    "notas_corazon": ["nuez moscada", "azahar"],
    "notas_fondo": ["haba tonka", "ámbar"],
    "intensidad": "Fuerte",
    "duracion": 9,
    "clima": "Frío",
    "ocasion": "Noche / formal",
    "genero": "Masculino"
  },
  {
    "nombre": "My Way",
    "marca": "Armani",
    "familia": "Floral",
    "notas_salida": ["bergamota", "azahar"],
    "notas_corazon": ["tuberosa", "jazmín"],
    "notas_fondo": ["vainilla", "cedro"],
    "intensidad": "Moderada",
    "duracion": 6,
    "clima": "Primavera",
    "ocasion": "Diario",
    "genero": "Femenino"
  },
  {
    "nombre": "Armani Mania",
    "marca": "Armani",
    "familia": "Amaderado Aromático",
    "notas_salida": ["mandarina", "azafrán"],
    "notas_corazon": ["vetiver", "cedro"],
    "notas_fondo": ["almizcle", "ámbar"],
    "intensidad": "Moderada",
    "duracion": 6,
    "clima": "Otoño",
    "ocasion": "Casual",
    "genero": "Masculino"
  },
  {
    "nombre": "Emporio Armani She",
    "marca": "Armani",
    "familia": "Ámbar Floral",
    "notas_salida": ["piña", "bergamota"],
    "notas_corazon": ["lirios", "jazmín"],
    "notas_fondo": ["vainilla", "almizcle"],
    "intensidad": "Moderada",
    "duracion": 6,
    "clima": "Templado",
    "ocasion": "Casual",
    "genero": "Femenino"
  },
  {
    "nombre": "Armani Prive Rose d’Arabie",
    "marca": "Armani",
    "familia": "Oriental Floral",
    "notas_salida": ["rosa"],
    "notas_corazon": ["azafrán"],
    "notas_fondo": ["patchouli", "ámbar"],
    "intensidad": "Fuerte",
    "duracion": 10,
    "clima": "Frío",
    "ocasion": "Formal / noche",
    "genero": "Unisex"
  },
{
    "nombre": "Good Girl",
    "marca": "Carolina Herrera",
    "familia": "Oriental Floral",
    "notas_salida": ["almendra", "café"],
    "notas_corazon": ["jazmín sambac", "nardo"],
    "notas_fondo": ["cacao", "vainilla", "tonka"],
    "intensidad": "Fuerte",
    "duracion": 9,
    "clima": "Frío",
    "ocasion": "Noche",
    "genero": "Femenino"
  },
  {
    "nombre": "Good Girl Supreme",
    "marca": "Carolina Herrera",
    "familia": "Oriental Dulce",
    "notas_salida": ["frutos rojos"],
    "notas_corazon": ["jazmín"],
    "notas_fondo": ["haba tonka", "vetiver"],
    "intensidad": "Fuerte",
    "duracion": 10,
    "clima": "Frío",
    "ocasion": "Noche / fiesta",
    "genero": "Femenino"
  },
  {
    "nombre": "212 VIP",
    "marca": "Carolina Herrera",
    "familia": "Oriental Vainilla",
    "notas_salida": ["ron", "maracuyá"],
    "notas_corazon": ["gardenia"],
    "notas_fondo": ["vainilla", "almizcle"],
    "intensidad": "Fuerte",
    "duracion": 8,
    "clima": "Noche",
    "ocasion": "Fiesta",
    "genero": "Femenino"
  },
  {
    "nombre": "212 VIP Men",
    "marca": "Carolina Herrera",
    "familia": "Amaderado Especiado",
    "notas_salida": ["limón", "jengibre"],
    "notas_corazon": ["vodka", "menta"],
    "notas_fondo": ["árbol ambarado", "cuero"],
    "intensidad": "Fuerte",
    "duracion": 8,
    "clima": "Frío",
    "ocasion": "Fiesta / noche",
    "genero": "Masculino"
  },
  {
    "nombre": "212 Sexy",
    "marca": "Carolina Herrera",
    "familia": "Oriental Vainilla",
    "notas_salida": ["pimienta rosa", "mandarina"],
    "notas_corazon": ["rosa", "gardena"],
    "notas_fondo": ["vainilla", "sándalo"],
    "intensidad": "Moderada",
    "duracion": 7,
    "clima": "Otoño",
    "ocasion": "Romántica",
    "genero": "Femenino"
  },
  {
    "nombre": "CH Men",
    "marca": "Carolina Herrera",
    "familia": "Amaderado Especiado",
    "notas_salida": ["toronja", "bergamota"],
    "notas_corazon": ["azafrán", "nuez moscada"],
    "notas_fondo": ["cuero", "vainilla"],
    "intensidad": "Moderada",
    "duracion": 7,
    "clima": "Otoño",
    "ocasion": "Casual / romántica",
    "genero": "Masculino"
  },
  {
    "nombre": "CH Women",
       "marca": "Carolina Herrera",
    "familia": "Floral Oriental",
    "notas_salida": ["bergamota", "pomelo"],
    "notas_corazon": ["rosa", "jazmín"],
    "notas_fondo": ["praliné", "canela", "sándalo"],
    "intensidad": "Moderada",
    "duracion": 6,
    "clima": "Primavera",
    "ocasion": "Diario",
    "genero": "Femenino"
  },
  {
    "nombre": "Very Good Girl",
    "marca": "Carolina Herrera",
    "familia": "Floral Frutal",
    "notas_salida": ["lichi", "grosella roja"],
    "notas_corazon": ["rosa"],
    "notas_fondo": ["vainilla", "vetiver"],
    "intensidad": "Moderada",
    "duracion": 7,
    "clima": "Primavera",
    "ocasion": "Romántica",
    "genero": "Femenino"
  },
  {
    "nombre": "Bad Boy",
    "marca": "Carolina Herrera",
    "familia": "Oriental Especiado",
    "notas_salida": ["pimienta negra", "bergamota"],
    "notas_corazon": ["cedro", "salvia"],
    "notas_fondo": ["cacao", "tonka"],
    "intensidad": "Fuerte",
    "duracion": 7,
    "clima": "Frío",
    "ocasion": "Noche",
    "genero": "Masculino"
  },
  {
    "nombre": "Bad Boy Le Parfum",
    "marca": "Carolina Herrera",
    "familia": "Cuero Aromático",
    "notas_salida": ["cáñamo", "pomelo"],
    "notas_corazon": ["pimienta negra", "geranio"],
    "notas_fondo": ["cuero", "vetiver"],
    "intensidad": "Fuerte",
    "duracion": 8,
    "clima": "Frío",
    "ocasion": "Noche / formal",
    "genero": "Masculino"
  },
   {
        "nombre": "Dylan Blue Pour Femme",
        "marca": "Versace",
        "familia": "Floral Frutal",
        "notas_salida": ["manzana verde", "grosella negra", "trébol"],
        "notas_corazon": ["melocotón", "jazmín", "rosa"],
        "notas_fondo": ["musk", "estoraque", "patchouli"],
        "intensidad": "moderada",
        "duracion": 7,
        "clima": "todo el año",
        "ocasion": "diario",
        "genero": "femenino"
    },
    {
        "nombre": "Bright Crystal",
        "marca": "Versace",
        "familia": "Floral Fresco",
        "notas_salida": ["granada", "yuzu"],
        "notas_corazon": ["peonía", "magnolia", "loto"],
        "notas_fondo": ["ámbar", "madera", "musk"],
        "intensidad": "suave",
        "duracion": 5,
        "clima": "verano",
        "ocasion": "casual",
        "genero": "femenino"
    },
    {
        "nombre": "Crystal Noir",
        "marca": "Versace",
        "familia": "Oriental Floral",
        "notas_salida": ["jengibre", "cardamomo", "pimienta"],
        "notas_corazon": ["coco", "gardenia", "peonía"],
        "notas_fondo": ["sándalo", "almizcle", "ámbar"],
        "intensidad": "fuerte",
        "duracion": 8,
        "clima": "frío",
        "ocasion": "noche",
        "genero": "femenino"
    },
    {
        "nombre": "Versace Pour Homme",
        "marca": "Versace",
        "familia": "Aromático Fresco",
        "notas_salida": ["limón", "bergamota", "rosa"],
        "notas_corazon": ["salvia", "cedro", "jacinto"],
        "notas_fondo": ["almizcle", "ámbar", "tonka"],
        "intensidad": "moderada",
        "duracion": 6,
        "clima": "calor",
        "ocasion": "diario",
        "genero": "masculino"
    },
    {
        "nombre": "Eros Pour Femme",
        "marca": "Versace",
        "familia": "Floral Amaderado",
        "notas_salida": ["limón", "bergamota", "granada"],
        "notas_corazon": ["jazmín", "peonía"],
        "notas_fondo": ["musk", "madera", "sándalo"],
        "intensidad": "moderada",
        "duracion": 7,
        "clima": "primavera",
        "ocasion": "romántica",
        "genero": "femenino"
    },
    {
        "nombre": "Eros Pour Homme",
        "marca": "Versace",
        "familia": "Aromático Vainilla",
        "notas_salida": ["menta", "manzana verde", "limón"],
        "notas_corazon": ["haba tonka", "geranio"],
        "notas_fondo": ["vainilla", "cedro", "vetiver"],
        "intensidad": "fuerte",
        "duracion": 10,
        "clima": "frío",
        "ocasion": "noche",
        "genero": "masculino"
    },
    {
        "nombre": "Versense",
        "marca": "Versace",
        "familia": "Cítrico Verde",
        "notas_salida": ["bergamota", "higo"],
        "notas_corazon": ["cardamomo", "jazmín"],
        "notas_fondo": ["cedro", "madera de olivo", "musk"],
        "intensidad": "suave",
        "duracion": 4,
        "clima": "verano",
        "ocasion": "diario",
        "genero": "femenino"
    },
    {
        "nombre": "Pour Femme Dylan Turquoise",
        "marca": "Versace",
        "familia": "Cítrico Acuático",
        "notas_salida": ["limón", "mandarina", "pimienta rosa"],
        "notas_corazon": ["jazmín", "freesia"],
        "notas_fondo": ["madera clara", "musk"],
        "intensidad": "moderada",
        "duracion": 6,
        "clima": "calor",
        "ocasion": "casual",
        "genero": "femenino"
    },
    {
        "nombre": "Versace Man Eau Fraîche",
        "marca": "Versace",
        "familia": "Acuático Maderoso",
        "notas_salida": ["limón", "bergamota", "carambola"],
        "notas_corazon": ["cedro", "estragón"],
        "notas_fondo": ["ámbar", "madera", "musk"],
        "intensidad": "suave",
        "duracion": 4,
        "clima": "verano",
        "ocasion": "diario",
        "genero": "masculino"
    },
    {
        "nombre": "Red Jeans",
        "marca": "Versace",
        "familia": "Floral Frutal",
        "notas_salida": ["durazno", "albaricoque", "fresa"],
        "notas_corazon": ["violeta", "rosa", "lirio"],
        "notas_fondo": ["vainilla", "madera"],
        "intensidad": "moderada",
        "duracion": 5,
        "clima": "primavera",
        "ocasion": "casual",
        "genero": "femenino"
    },
      {
        "nombre": "Purr",
        "marca": "Katy Perry",
        "familia": "Floral Frutal",
        "notas_salida": ["durazno", "manzana roja", "gardenia"],
        "notas_corazon": ["jazmín", "rosa búlgara", "bambú"],
        "notas_fondo": ["musk", "ámbar", "sándalo"],
        "intensidad": "moderada",
        "duracion": 6,
        "clima": "todo el año",
        "ocasion": "casual",
        "genero": "femenino"
    },
    {
        "nombre": "Meow",
        "marca": "Katy Perry",
        "familia": "Dulce Frutal",
        "notas_salida": ["mandarina", "pera"],
        "notas_corazon": ["jazmín", "gardenia"],
        "notas_fondo": ["vainilla", "almizcle", "sándalo"],
        "intensidad": "suave",
        "duracion": 5,
        "clima": "primavera",
        "ocasion": "diario",
        "genero": "femenino"
    },
    {
        "nombre": "Killer Queen",
        "marca": "Katy Perry",
        "familia": "Oriental Floral",
        "notas_salida": ["ciruela", "bergamota"],
        "notas_corazon": ["jazmín", "frangipani"],
        "notas_fondo": ["praliné", "madera", "patchouli"],
        "intensidad": "fuerte",
        "duracion": 8,
        "clima": "frío",
        "ocasion": "noche",
        "genero": "femenino"
    },
    {
        "nombre": "Killer Queen Oh So Sheer",
        "marca": "Katy Perry",
        "familia": "Frutal Floral",
        "notas_salida": ["uva", "ciruela"],
        "notas_corazon": ["freesia", "jazmín"],
        "notas_fondo": ["madera clara", "musk"],
        "intensidad": "suave",
        "duracion": 4,
        "clima": "verano",
        "ocasion": "casual",
        "genero": "femenino"
    },
    {
        "nombre": "Killer Queen Oh So Royal",
        "marca": "Katy Perry",
        "familia": "Floral Frutal",
        "notas_salida": ["pomelo", "frambuesa"],
        "notas_corazon": ["fresia", "jazmín"],
        "notas_fondo": ["almizcle", "praliné"],
        "intensidad": "moderada",
        "duracion": 6,
        "clima": "primavera",
        "ocasion": "diario",
        "genero": "femenino"
    },
    {
        "nombre": "Mad Potion",
        "marca": "Katy Perry",
        "familia": "Dulce Gourmand",
        "notas_salida": ["vainilla", "orquídea"],
        "notas_corazon": ["jazmín", "peonía"],
        "notas_fondo": ["almizcle", "almendra"],
        "intensidad": "moderada",
        "duracion": 5,
        "clima": "frío",
        "ocasion": "casual",
        "genero": "femenino"
    },
    {
        "nombre": "Mad Love",
        "marca": "Katy Perry",
        "familia": "Frutal Dulce",
        "notas_salida": ["manzana", "toronja"],
        "notas_corazon": ["jazmín", "fresa"],
        "notas_fondo": ["madera clara", "almizcle"],
        "intensidad": "suave",
        "duracion": 4,
        "clima": "verano",
        "ocasion": "casual",
        "genero": "femenino"
    },
    {
        "nombre": "Indi",
        "marca": "Katy Perry",
        "familia": "Floral Amaderado",
        "notas_salida": ["ciruela", "té blanco"],
        "notas_corazon": ["rosa", "muguet"],
        "notas_fondo": ["almizcle", "ámbar"],
        "intensidad": "moderada",
        "duracion": 7,
        "clima": "otoño",
        "ocasion": "diario",
        "genero": "femenino"
    },
    {
        "nombre": "Indi Visible",
        "marca": "Katy Perry",
        "familia": "Dulce Floral",
        "notas_salida": ["vainilla", "mora"],
        "notas_corazon": ["peonía", "jazmín"],
        "notas_fondo": ["almizcle", "madera"],
        "intensidad": "moderada",
        "duracion": 6,
        "clima": "todo el año",
        "ocasion": "casual",
        "genero": "femenino"
    },
    {
        "nombre": "Mad Potion Shine",
        "marca": "Katy Perry",
        "familia": "Floral Dulce",
        "notas_salida": ["caramelo"],
        "notas_corazon": ["rosa", "jazmín"],
        "notas_fondo": ["vainilla", "almizcle"],
        "intensidad": "moderada",
        "duracion": 5,
        "clima": "primavera",
        "ocasion": "casual",
        "genero": "femenino"
    },
     {
        "nombre": "Ari",
        "marca": "Ariana Grande",
        "familia": "Floral Frutal Dulce",
        "notas_salida": ["pera", "toronja", "frambuesa"],
        "notas_corazon": ["orquídea", "rosa"],
        "notas_fondo": ["malvavisco", "musk", "madera"],
        "intensidad": "moderada",
        "duracion": 6,
        "clima": "todo el año",
        "ocasion": "diario",
        "genero": "femenino"
    },
    {
        "nombre": "Cloud",
        "marca": "Ariana Grande",
        "familia": "Dulce Gourmand",
        "notas_salida": ["lavanda", "pera"],
        "notas_corazon": ["crema batida", "praliné", "coco"],
        "notas_fondo": ["musk", "madera"],
        "intensidad": "moderada",
        "duracion": 7,
        "clima": "frío",
        "ocasion": "diario",
        "genero": "femenino"
    },
    {
        "nombre": "Cloud 2.0 Intense",
        "marca": "Ariana Grande",
        "familia": "Dulce Cremoso",
        "notas_salida": ["lavanda", "bergamota"],
        "notas_corazon": ["praliné", "coco", "vainilla"],
        "notas_fondo": ["almizcle", "madera"],
        "intensidad": "fuerte",
        "duracion": 9,
        "clima": "frío",
        "ocasion": "noche",
        "genero": "femenino"
    },
    {
        "nombre": "Sweet Like Candy",
        "marca": "Ariana Grande",
        "familia": "Dulce Frutal",
        "notas_salida": ["mora", "pera"],
        "notas_corazon": ["frangipani", "jazmín"],
        "notas_fondo": ["vainilla", "musk"],
        "intensidad": "moderada",
        "duracion": 6,
        "clima": "todo el año",
        "ocasion": "casual",
        "genero": "femenino"
    },
    {
        "nombre": "Sweet Like Candy Limited",
        "marca": "Ariana Grande",
        "familia": "Frutal Dulce",
        "notas_salida": ["arándanos", "frambuesa"],
        "notas_corazon": ["jazmín", "rosa"],
        "notas_fondo": ["vainilla", "crema"],
        "intensidad": "moderada",
        "duracion": 5,
        "clima": "primavera",
        "ocasion": "casual",
        "genero": "femenino"
    },
    {
        "nombre": "Moonlight",
        "marca": "Ariana Grande",
        "familia": "Dulce Floral",
        "notas_salida": ["ciruela", "grosella"],
        "notas_corazon": ["peonía", "flor de tiaré"],
        "notas_fondo": ["vainilla", "musk", "sándalo"],
        "intensidad": "moderada",
        "duracion": 7,
        "clima": "otoño",
        "ocasion": "romántica",
        "genero": "femenino"
    },
    {
        "nombre": "Thank U Next",
        "marca": "Ariana Grande",
        "familia": "Dulce Cremoso",
        "notas_salida": ["pera", "frambuesa"],
        "notas_corazon": ["coco", "rosa"],
        "notas_fondo": ["macarrón", "musk"],
        "intensidad": "moderada",
        "duracion": 6,
        "clima": "primavera",
        "ocasion": "casual",
        "genero": "femenino"
    },
    {
        "nombre": "Thank U Next 2.0",
        "marca": "Ariana Grande",
        "familia": "Frutal Dulce",
        "notas_salida": ["manzana", "fresa"],
        "notas_corazon": ["coco", "jazmín"],
        "notas_fondo": ["almizcle", "madera"],
        "intensidad": "moderada",
        "duracion": 5,
        "clima": "verano",
        "ocasion": "casual",
        "genero": "femenino"
    },
    {
        "nombre": "God is a Woman",
        "marca": "Ariana Grande",
        "familia": "Floral Frutal",
        "notas_salida": ["pera", "ambrette"],
        "notas_corazon": ["rosas turcas", "iris"],
        "notas_fondo": ["madera", "musk"],
        "intensidad": "suave",
        "duracion": 5,
        "clima": "primavera",
        "ocasion": "diario",
        "genero": "femenino"
    },
    {
        "nombre": "Mod Vanilla",
        "marca": "Ariana Grande",
        "familia": "Dulce Vainilla",
        "notas_salida": ["ciruela", "almendra"],
        "notas_corazon": ["praliné", "vainilla"],
        "notas_fondo": ["musk", "ámbar"],
        "intensidad": "fuerte",
        "duracion": 8,
        "clima": "frío",
        "ocasion": "noche",
        "genero": "femenino"
    }
]
